name: Release
on:
  release:
    types: [created]
env:
  NODE_VER: 16.x
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install cargo contract
      run: |
        rustup component add rust-src
        sudo apt-get install binaryen
        cargo install cargo-dylint dylint-link
        cargo install --force --locked cargo-contract

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VER }}

    - name: Install dependencies
      run: yarn

    - name: yarn test
      run: yarn test

    - name: yarn build
      run: yarn build

    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
