name: Tests
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:
jobs:
  tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Install cargo contract
      run: |
        apt-get install binaryen
        cargo install cargo-dylint dylint-link
        cargo install --force --locked cargo-contract

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: yarn

    - name: yarn test
      run: yarn test
